export const Button = require('antd/lib/button')
export const Icon = require('antd/lib/icon')

export const Row = require('antd/lib/row')
export const Col = require('antd/lib/col')
export const Layout = require('antd/lib/layout')

export const Affix = require('antd/lib/affix')
export const Breadcrumb = require('antd/lib/breadcrumb')
export const Dropdown = require('antd/lib/dropdown')
export const Menu = require('antd/lib/menu')
export const Pagination = require('antd/lib/pagination')
export const Steps = require('antd/lib/steps')

export const AutoComplete = require('antd/lib/auto-complete')
export const Cascader = require('antd/lib/cascader')
export const Checkbox = require('antd/lib/checkbox')
export const DatePicker = require('antd/lib/date-picker')
export const Form = require('antd/lib/form')
export const Input = require('antd/lib/input')
export const InputNumber = require('antd/lib/input-number')
export const Mention = require('antd/lib/mention')
export const Radio = require('antd/lib/radio')
export const Rate = require('antd/lib/rate')
export const Select = require('antd/lib/select')
export const Skeleton = require('antd/lib/skeleton')
export const Switch = require('antd/lib/switch')
export const Slider = require('antd/lib/slider')
export const TreeSelect = require('antd/lib/tree-select')
export const TimePicker = require('antd/lib/time-picker')
export const Transfer = require('antd/lib/transfer')
export const Upload = require('antd/lib/upload')

export const Avatar = require('antd/lib/avatar')
export const Badge = require('antd/lib/badge')
export const Calendar = require('antd/lib/calendar')
export const Card = require('antd/lib/card')
export const Carousel = require('antd/lib/carousel')
export const Collapse = require('antd/lib/collapse')
export const List = require('antd/lib/list')
export const Popover = require('antd/lib/popover')
export const Tooltip = require('antd/lib/tooltip')
export const Table = require('antd/lib/table')
export const Tabs = require('antd/lib/tabs')
export const Tag = require('antd/lib/tag')
export const Timeline = require('antd/lib/timeline')
export const Tree = require('antd/lib/tree')

export const Alert = require('antd/lib/alert')
export const Drawer = require('antd/lib/drawer')
export const Modal = require('antd/lib/modal')
export const Message = require('antd/lib/message')
export const Notification = require('antd/lib/notification')
export const Progress = require('antd/lib/progress')
export const Popconfirm = require('antd/lib/popconfirm')
export const Spin = require('antd/lib/spin')

export const Anchor = require('antd/lib/anchor')
export const BackTop = require('antd/lib/back-top')
export const Divider = require('antd/lib/divider')
export const LocaleProvider = require('antd/lib/locale-provider')



